# This file is a template, and might need editing before it works on your project.
# see https://docs.gitlab.com/ee/ci/yaml/README.html for all available options

# you can delete this line if you're not using Docker

build1:
  stage: build
  script:
    - echo "Hello"
    - docker build -t dnacollector .

deploy1:
  stage: deploy
  script:
    - docker run -d --name dnacollector dnacollector
