dnac:
  ip: '1.1.1.1'
  username: 'notreal'
  password: 'notreal'
elastic: 
  ip: '1.1.1.1'
  username: 'notreal'
  password: 'notreal'
tenable:
  ip: '1.1.1.1'
  username: 'notreal'
  password: 'notreal'
